### PR TITLE
Use Go modules for coverage CI job

### PR DESCRIPTION
**Pull request by tnir**
Completely removes `server/.depensure` dependencies from Makefile

Complement of #5

### CODE REVIEW

**Comment by tnir** [comment]
CircleCI Pipeline for the PR: https://circleci.com/workflow-run/0f154711-b707-4eb8-a7b5-7fa19ed483cf

**Comment by cpanato** [comment]
why this not run on circleci?
@tnir can you push an empty commit to see if it will trigger circleci?

**Comment by tnir** [comment]
@cpanato Umm, you could see coverage job named as `plugin-ci/coverage` at https://circleci.com/gh/tnir/mattermost-plugin-aws-SNS/12 as part of https://github.com/mattermost/mattermost-plugin-aws-SNS/pull/26#issuecomment-523792379 . Or do you mean you want to see it at the original https://circleci.com/gh/mattermost/mattermost-plugin-aws-SNS ?

**Comment by tnir** [comment]
@cpanato Thanks. We would see the coverage reports at https://codecov.io/gh/mattermost/mattermost-plugin-aws-SNS when they are ready.

**Pull request merged**
