### PR TITLE
Add autocomplete functionality

### PR DESCRIPTION
**Pull request by jrepe**
#### Summary

This pull request adds slash command autocomplete functionality

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-aws-SNS/issues/39

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
LGTM :+1: Thanks @jrepe!

**Comment by jrepe** [comment]
Great, thanks 🎉

**Comment by hanzei** [comment]
@DHaussermann I've tested this PR locally and didn't found any issues on this PR.

One unrelated issue was found: Entering `/awssns` does crash the plugin. I will submit a separate PR for this.

**Review by DHaussermann — APPROVED** [review]
Thanks @hanzei  much appreciated.  And thanks to @jrepe for this contribution!

LGTM!

**Pull request merged**
